<a href="https://colab.research.google.com/github/imru123/numpy/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.How can I slice a 1-dimensional array in NumPy?

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a[1:3])

[2 3]


2.Can I slice a 2-dimensional array in NumPy?

In [ ]:
b=np.array([[2,3,4],[5,6,7]])
print(b[0,0:2])

[2 3]


3.How can I slice an array with a step in NumPy?

In [ ]:
print(a[::2])

[1 3 5]


4.Can I use negative indices for slicing in NumPy?

In [ ]:
print(a[-2:])

[4 5]


5.What happens if I omit the start or end index in a slice?

In [ ]:
print(a[:])

[1 2 3 4 5]


6.Can I modify the original array using slicing in NumPy?

In [ ]:
c=np.array([23,42,38,2,4])
print(c)
c[0]=100
print(c)

[23 42 38  2  4]
[100  42  38   2   4]


7.How can I slice a multi-dimensional array along a specific axis in NumPy?

8.Can I use boolean indexing for slicing in NumPy?

In [ ]:
arr0=np.array([1,2,3,4,5,6,7])
mask=np.array([True,True,False,True,False,False,True])
sliced_array=arr0[mask]
print(sliced_array)

[1 2 4 7]


9.How can I reverse the elements of an array using slicing in NumPy?

In [ ]:
print(a[::-1])

[5 4 3 2 1]


10.Can I use slicing to extract a sub-array from a higher-dimensional array in NumPy?

In [ ]:
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(d)
print(d[2,0:1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[13 14 15]]


11.How can I create a copy of a sliced array in NumPy?

In [ ]:
cc=np.array([1,3,5,7])
dd=cc.copy()
dd[1]=30
print(cc)
print(dd)

[1 3 5 7]
[ 1 30  5  7]


12. Can I use slicing to assign values to a subset of an array in NumPy?

In [ ]:
k=np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
print(k)
g=k[2,0:3]
k[0]+g

[[1 2 3]
 [3 4 5]
 [5 6 7]
 [7 8 9]]


array([ 6,  8, 10])

13.  Is it possible to slice an array with non-contiguous indices in NumPy?

In [ ]:
ab=np.array([1,2,3,4,5,6,7,8,9,10])
print(ab[::2])

[1 3 5 7 9]


14.  Can I use slicing to extract elements based on a condition in NumPy?

In [ ]:
h=np.array([23,94,12,40])
l=np.array([46,7,9,23])
h[l>10]

array([23, 40])

15.  How can I slice an array along multiple axes in NumPy? (To slice an array along multiple axes, you can use slicing syntax for each axis separated by commas)

In [ ]:
fh=np.array([[[1,2],[2,3]],[[3,4],[5,6]],[[7,8],[8,9]]])
print(fh)
print(fh[0,1,1])

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]

 [[7 8]
  [8 9]]]
3
